version: "3.9"

services:
    kafka-rust-producer:
        container_name: kafka-rust-producer
        build:
            context: ../../../
            dockerfile: ./.devops/docker/develop/Dockerfile
        volumes:
            - ../../..:/home/app
        networks:
            - app-network
            - kafka-network
            - cockroach-network
            -
    promtail:
        image: grafana/promtail:2.8.0
        volumes:
            - ../../../log:/var/log
            - ./promtail_config.yml:/etc/promtail/config.yml
        command: -config.file=/etc/promtail/config.yml

networks:
    app-network:
        driver: bridge
    kafka-network:
        external: true
    cockroach-network:
        external: true