version: "3.9"

services:
    kafka-rust-producer:
        container_name: kafka-rust-producer
        build:
            context: ../../../
            dockerfile: ./.devops/docker/develop/Dockerfile
        volumes:
            - ../../..:/home/app
        networks:
            - app-network
            - kafka-network
        logging:
            driver: loki
            options:
                loki-url: "http://10.0.0.3:3100/loki/api/v1/push"
networks:
    app-network:
        driver: bridge
    kafka-network:
        external: true